amazon:
       dynamodb:
          endpoint: dynamodb.us-east-1.amazonaws.com
          prefix: dev
       aws:
           accesskey: // KEY AWS
           secretkey: //KEY AWS
           region: //REGION
server:
    port: 8070

spring:
      jackson:
              serialization:
                           indent_output: true



cors.allowsorigins:  http://localhost:8070,http://localhost

